version: "3.9"

# Remote deployment – puller færdigt image fra ghcr.io, bygger ikke lokalt
services:
  api:
    image: ${IMAGE_NAME}:${IMAGE_TAG:-latest}   # Puller fra ghcr.io

  db:
     ports:
      - "127.0.0.1:3306:3306"   # Kun tilgængelig lokalt på remote VM – ikke udefra